### ISSUE TITLE
Would be great if it works with LINQPad 6

### ISSUE THREAD

**Issue by Sam558** [rdavisau/linqpad-dump-editable#1]
Great tool, thanks!
Any plan to make a .NET core 3.0 version? Got below warning when adding DumpEditable through Nuget in LINQPad 6.

![image](https://user-images.githubusercontent.com/5130163/63826040-ba1c5200-c922-11e9-93e4-c1c2b0580549.png)

**Comment by rdavisau** [comment]
Apologies, somehow I missed this issue! The good news is I just published a netcore3-friendly update the works with LINQPad6 🎉 

Let me know if you hit any issues.
